quiet: true
exit-code: 0
ignorefile: .trivyignore.yaml

scan:
  scanners:
    - vuln
    - misconfig
    - secret
  skip-dirs:
    - tests/
    - examples/

misconfiguration:
  include-non-failures: true
  scanners:
    - terraform
  terraform:
    exclude-downloaded-modules: false
