name: Continuous Integration

on:
  # Update based on the way you work: https://christosgalano.github.io/branch-deployment-models/
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event }}
  cancel-in-progress: true

jobs:
  terraform_scan:
    uses: ./.github/workflows/scan.yaml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

  terraform_test:
    uses: ./.github/workflows/test.yaml
    needs: terraform_scan
    secrets: inherit
    with:
      suite: 'contract'

  terraform_docs:
    name: Terraform Docs
    needs: terraform_test
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Run terraform-docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: .
          template: ""
          output-method: replace
          config-file: .terraform-docs.yaml
          git-push: "true"
