name: Terraform Scan

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event }}
  cancel-in-progress: true

jobs:
  terraform_scan:
    name: Scan Configuration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">= 1.8, < 2.0"

      - name: Terraform init
        run: terraform init

      - name: Terraform format check
        run: terraform fmt -check -no-color

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v4

      - name: Tflint scan
        run: |
          tflint --init --config .tflint.hcl
          tflint --config "$(pwd)/.tflint.hcl" --format junit > tflint_results_junit.xml

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-ref: .
          scan-type: fs
          output: trivy_results_junit.xml
          trivy-config: .trivy.yaml

      - name: Checkov scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          config_file: .checkov.yaml
          output_format: cli,junitxml
          output_file_path: console,checkov_results_junit.xml

      - name: Display results
        run: ls -al

      - name: Publish results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Scan Results
          files: '*_junit.xml'
          action_fail: true
