name: Terraform Test

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
        required: true
        description: 'Azure Service Principal Client ID'
      ARM_CLIENT_SECRET:
        required: true
        description: 'Azure Service Principal Client Secret'
      ARM_TENANT_ID:
        required: true
        description: 'Azure Service Principal Tenant ID'
      ARM_SUBSCRIPTION_ID:
        required: true
        description: 'Azure Service Principal Subscription ID'

jobs:
  terraform_test:
    name: Test Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">= 1.8, < 2.0"

      - name: Terraform init
        run: terraform init

      - name: Contract tests
        run: terraform test -filter=tests/contract.tftest.hcl

      - name: Integration tests
        run : terraform test -filter=tests/integration.tftest.hcl
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
